export const Database = [
    {ID:1, text:'Email', type:'success', addInfo:'Some important text Some important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important text', read:false, group:'C'},
    {ID:2, text:'Weather', type:'info', addInfo:'Some other text', read:false, group:'B'},
    {ID:3, text:'Spotify', type:'error', addInfo:'No internet connection', read:false, group:'D'},
    {ID:4, text:'Bank', type:'error', addInfo:'Not enough funds', read:false, group:'B'},
    {ID:5, text:'Email', type:'info', addInfo:'Update available', read:false, group:'C'},
    {ID:6, text:'Weather', type:'info', addInfo:'Forecast some dangerous stuff', read:false, group:'D'},
    {ID:7, text:'Spotify', type:'success', addInfo:'Songs downloaded successful', read:false, group:'B'},
    {ID:8, text:'Email', type:'error', addInfo:'No internet connection', read:false, group:'C'},
    {ID:9, text:'Bank', type:'error', addInfo:'Not enough funds', read:false, group:'D'},
    {ID:10, text:'Email', type:'info', addInfo:'Update available', read:false, group:'B'},
    {ID:11, text:'Weather', type:'warning', addInfo:'Forecast some dangerous stuff', read:false, group:'B'},
    {ID:12, text:'Spotify', type:'success', addInfo:'Songs downloaded successful', read:false, group:'C'},
    {ID:13, text:'Bank', type:'success', addInfo:'Money transfer completed', read:false, group:'B'},
    {ID:14, text:'Email', type:'warning', addInfo:'Some important text Some important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important text', read:false, group:'C'},
    {ID:15, text:'Weather', type:'info', addInfo:'Some other text', read:false, group:'A'},
    {ID:16, text:'Email', type:'success', addInfo:'Money transfer completed', read:false, group:'D'},
    {ID:17, text:'Email', type:'warning', addInfo:'Some important text Some important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important textSome important text', read:false, group:'A'},
    {ID:18, text:'Weather', type:'info', addInfo:'Some other text', read:false, group:'A'},
    {ID:19, text:'Spotify', type:'error', addInfo:'No internet connection', read:false, group:'A'},
    {ID:20, text:'Bank', type:'info', addInfo:'Not enough funds', read:false, group:'D'},
    {ID:21, text:'Email', type:'info', addInfo:'Update available', read:false, group:'A'},
    {ID:22, text:'Weather', type:'warning', addInfo:'Forecast some dangerous stuff', read:true, group:'C'},
    {ID:23, text:'Spotify', type:'success', addInfo:'Songs downloaded successful', read:true, group:'D'},
    {ID:24, text:'Bank', type:'success', addInfo:'Money transfer completed', read:true, group:'D'},
];